### PR TITLE
Slightly improved ass support

### PR DESCRIPTION
**Pull request by theunbound**
Fixed a few potential problems.

### CODE REVIEW

**Comment by jamiees2** [comment]
Cool! I'll take a better look at this tomorrow, but it looks good :)

**Comment by theunbound** [comment]
*bump?*

I'd like to be able to pull this from npm some time in the coming week, if you want to accept my pull request.

**Comment by jamiees2** [comment]
Wow sorry, I completely forgot about this, I apologize! Anyway LGTM :)

**Review by jamiees2 — APPROVED** [review]

**Comment by jamiees2** [comment]
And published as version 1.2.0 in NPM :)

**Pull request merged**
